CREATE TABLE IF NOT EXISTS expenses(
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_user INT NOT NULL,
    id_year INT NOT NULL,
    id_month INT NOT NULL,
    description VARCHAR(255) NOT NULL,
    import DOUBLE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES users(id),
    FOREIGN KEY (id_year) REFERENCES years(id),
    FOREIGN KEY (id_month) REFERENCES months(id)
);